config/routes.rb
Rails.application.routes.draw do
 

  root "tags#index"
  resources :tags

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord


  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/car.rb
class Car < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/tag.rb
class Tag < ApplicationRecord

	 validates :email, presence: true
	 	 validates :username, presence: true
  validates :password, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    http_basic_authenticate_with name: "Abed", password: "A123", except: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
  	 @cars = Car.all
  end
  def show
  	@car = Car.find(params[:id])
  end


  def new
    @car = Car.new
  end

  def create
    @car = Car.new(title: "...", body: "...")

    if @car.save
      redirect_to @car
    else
      render :new
    end
  end


  
  private
    def car_params
      params.require(:car).permit(:title, :body)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def create
         @tag = Tag.new(tag_params)


    if @tag.save
      redirect_to @tag
    else
      render :new
    end
  end

def Auth

	@tag= Tag.new

      render :login
     
      end



    

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to @tag
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to root_path
  end

  private
    def tag_params
      params.require(:tag).permit(:email, :username, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = Users.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/tagggs_helper.rb
module TagggsHelper
end

app/helpers/taggs_helper.rb
module TaggsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/cars/index.html.erb
<h1>Cars</h1>



<ul>
  <% @cars.each do |car| %>
    <li>
      <%= link_to car.title, car %>
    </li>
  <% end %>
</ul>

<%= link_to "New Car", new_car_path %>

app/views/cars/new.erb
<h1>New Car</h1>

<%= form_with model: @car do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @car.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @car.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<form action="/cars" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="...">

  <div>
    <label for="car_title">Title</label><br>
    <input type="text" name="car[title]" id="car_title">
  </div>

  <div>
    <label for="car_body">Body</label><br>
    <textarea name="car[body]" id="car_body"></textarea>
  </div>

  <div>
    <input type="submit" name="commit" value="Create Car" data-disable-with="Create Car">
  </div>
</form>

app/views/cars/show.erb
<h1><%= @car.title %></h1>

<p><%= @car.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.erb
<%= form_with model: tag do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% tag.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :username %><br>
    <%= form.text_area :username %><br>
    <% tag.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %><br>
    <% tag.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.erb
<h1>Edit Tag</h1>

<%= render "form", tag: @tag %>

app/views/tags/index.html.erb
<h1>List of  user</h1>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.username, tag %>
    </li>
  <% end %>
</ul>

<%= link_to "New Tag", new_tag_path %>

app/views/tags/login.erb
<h1>login</h1>

<%= form_with model: @tag do |form| %>
   <div>
    <%= form.label :username %><br>
    <%= form.text_area :username %><br>
    <% @tag.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %><br>
    <% @tag.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
 <%= form.submit %>
  <div>
  </div>

<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= form_with model: @tag do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @tag.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :username %><br>
    <%= form.text_area :username %><br>
    <% @tag.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %><br>
    <% @tag.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.email%></h1>

<p><%= @tag.username %></p>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.title %>
    </li>
  <% end %>
</ul>